CREATE VIEW [PERSON_DATA] AS
(SELECT [FIRST_NAME],[SECOND_NAME],[LAST_NAME] , [P_N].[PHONE_NUMBER] , [P_T].[PHONE_TYPE]
	FROM [PERSONS] AS [P]
	LEFT JOIN [PHONE_NUMBERS]
		AS P_N
			ON
				[P_N].PERSON_ID = P.[ID]
	LEFT JOIN [PHONE_TYPES]
		AS [P_T] 
			ON
				[P_T].[ID] = [P_N].[PHONE_TYPE_ID])


SELECT
	[FIRST_NAME] AS [Име],
	[LAST_NAME] AS [Фамилия],
	[C].[CITY_NAME] AS [Град]
FROM [PERSONS] AS [P]
LEFT JOIN [CITIES]
		AS [C]
			ON
				C.ID = P.[CITY_ID]



CREATE VIEW [PERSONS_FROM_BURGAS] AS 
SELECT [FIRST_NAME],[LAST_NAME], [C].[CITY_NAME]
	FROM [PERSONS] AS [P]
	LEFT JOIN [CITIES]
		AS [C]
			ON 
				[C].[ID] = [P].CITY_ID
	WHERE
		[C].CITY_NAME = 'Бургас'


CREATE VIEW [COUNT_PERSONS_FROM_BURGAS] AS
	(SELECT COUNT(C.[ID]) AS [CITIES_COUNT] FROM 
		[PERSONS] AS [P]
		LEFT JOIN [CITIES] AS [C] ON [P].CITY_ID = [C].[ID]
	WHERE [C].[CITY_NAME]='Бургас')


SELECT  [C].[CITY_NAME]
	FROM [PERSONS] AS [P]
	LEFT JOIN [CITIES]
		AS [C]
			ON 
				[C].[ID] = [P].CITY_ID
GROUP BY C.CITY_NAME


SELECT [FIRST_NAME],[SECOND_NAME],[LAST_NAME] , [P_N].[PHONE_NUMBER]
	FROM [PERSONS] AS [P]
	LEFT JOIN [PHONE_NUMBERS]
		AS P_N
			ON
				[P_N].PERSON_ID = P.[ID]
	WHERE [P_N].[PHONE_NUMBER] LIKE '089%'


SELECT [FIRST_NAME],[LAST_NAME] , [P_N].[PHONE_NUMBER]
	FROM [PERSONS] AS [P]
	LEFT JOIN [PHONE_NUMBERS]
		AS P_N
			ON
				[P_N].PERSON_ID = P.[ID]
	WHERE [P_N].[PHONE_NUMBER] LIKE '%9'

SELECT [FIRST_NAME],[LAST_NAME]
	FROM [PERSONS] 
	WHERE [FIRST_NAME] LIKE 'Х%' AND
			[LAST_NAME] LIKE 'П%'


SELECT [FIRST_NAME],[LAST_NAME]
	 FROM [PERSONS] 
	 WHERE [LAST_NAME] LIKE '%В'


SELECT * FROM [PHONE_TYPES]
SELECT * FROM [CITIES]
SELECT * FROM [PHONE_NUMBERS]
SELECT * FROM [PERSONS]
