
SELECT * FROM [PERSONS]

SELECT [FIRST_NAME],[SECOND_NAME],[LAST_NAME] , [P_N].[PHONE_NUMBER] , [P_T].[PHONE_TYPE]
FROM [PERSONS] AS [P]
LEFT JOIN [PHONE_NUMBERS] AS P_N ON [P_N].PERSON_ID = P.[ID]
LEFT JOIN [PHONE_TYPES] AS [P_T] ON [P_T].[ID] = [P_N].[PHONE_TYPE_ID]

SELECT * FROM [PHONE_NUMBERS]