USE [PhoneBook]

CREATE TABLE
	[CITIES]
	(
		[ID]
			INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER]
			INT,
		[CITY_NAME]
			NVARCHAR(50)NOT NULL,
		[AREA_NAME]
			NVARCHAR(40)NOT NULL,
		[POSTAL_CODE]
			INT NOT NULL,
		CONSTRAINT [PK_CITIES_ID]
		PRIMARY KEY CLUSTERED ([ID])
	)


CREATE TABLE
	[PHONE_TYPES]
	(
		[ID]
			INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER]
			INT,
		[PHONE_TYPE]
			VARCHAR(6),
		CONSTRAINT
			[CK_PHONE_TYPES_PHONE_TYPE]
				CHECK (
						[PHONE_TYPE]='mobile' 
						OR [PHONE_TYPE]='home'
						OR [PHONE_TYPE]='work'
					  ),
		CONSTRAINT [PK_PHONE_TYPES_ID]
		PRIMARY KEY CLUSTERED ([ID])
	)

CREATE TABLE
	[PERSONS]
	(
		[ID]
			INT
			IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER]
			INT,
		[FIRST_NAME]
			NVARCHAR(40) NOT NULL,
		[SECOND_NAME]
			NVARCHAR(40) NOT NULL,
		[LAST_NAME]
			NVARCHAR(50) NOT NULL,
		[CITY_ID]
			INT NOT NULL,
		[ADDRESS]
			NVARCHAR(200) NOT NULL,
		CONSTRAINT
				[FK_PERSONS_CITY_ID] 
		FOREIGN KEY
				([CITY_ID])
		REFERENCES
				[CITIES]([ID]),
		CONSTRAINT [PK_PERSONS_ID]
			PRIMARY KEY CLUSTERED([ID])
	)

CREATE TABLE
	[PHONE_NUMBERS]
	(
		[ID] INT IDENTITY (1,1) NOT NULL, 
		[UPDATE_COUNTER]
			INT,
		[PERSON_ID]
			INT NOT NULL,
		[PHONE_TYPE_ID]
			INT NOT NULL,
		[PHONE_NUMBER]
		VARCHAR(10) NOT NULL,
		CONSTRAINT CK_PHONE_NUMBERS_PHONE_NUMBER
			CHECK (LEN([PHONE_NUMBER])=1 ),
		CONSTRAINT [FK_PHONE_NUMBERS_PERSON_ID]
			FOREIGN KEY  ([PERSON_ID]) 
			REFERENCES [PERSONS] ([ID]),
		CONSTRAINT [FK_PHONE_NUMBERS_PHONE_TYPE_ID]
			FOREIGN KEY ([PHONE_TYPE_ID])
			REFERENCES [PHONE_TYPES] ([ID]),
		CONSTRAINT [PK_PHONE_NUMBERS_ID]
			PRIMARY KEY CLUSTERED([ID])
	)