USE [PhoneBook]

DROP VIEW IF EXISTS [PERSON_DATA]

CREATE VIEW [PERSON_DATA] AS
SELECT [FIRST_NAME],
		[SECOND_NAME],
		[LAST_NAME] ,
		[PHONE_NUMBERS].[PHONE_NUMBER],
		[PHONE_TYPES].[PHONE_TYPE]
	FROM [PERSONS]
	LEFT JOIN [PHONE_NUMBERS]
			ON [PHONE_NUMBERS].PERSON_ID = [PERSONS].[ID]
	LEFT JOIN [PHONE_TYPES] 
			ON
				[PHONE_TYPES].[ID] = [PHONE_NUMBERS].[PHONE_TYPE_ID]


SELECT * FROM [PERSONS]
RIGHT JOIN [CITIES] ON [PERSONS].[CITY_ID] = [CITIES].[ID]


SELECT [FIRST_NAME] AS [Име],
	   [LAST_NAME] AS [Фамилия],
	   [CITIES].[CITY_NAME] AS [Град]
FROM [PERSONS]
	LEFT JOIN [CITIES] ON [CITIES].[ID] = [PERSONS].[CITY_ID]


DROP VIEW IF EXISTS [COUNT_PERSONS_FROM_BURGAS]

CREATE VIEW [COUNT_OF_PERSONS_FROM_BURGAS] AS
	(SELECT COUNT([CITIES].[ID]) AS [CITIES_COUNT] FROM [PERSONS]
		LEFT JOIN [CITIES] ON [PERSONS].CITY_ID = [CITIES].[ID]
	WHERE [CITIES].[CITY_NAME]='Бургас')


SELECT  [CITIES].[CITY_NAME] FROM [PERSONS] 
	LEFT JOIN [CITIES] ON [CITIES].[ID] = [PERSONS].CITY_ID
GROUP BY [CITIES].[CITY_NAME]


SELECT [FIRST_NAME],
	   [SECOND_NAME],
	   [LAST_NAME] ,
	   [PHONE_NUMBERS].[PHONE_NUMBER]
	FROM [PERSONS] 
	LEFT JOIN [PHONE_NUMBERS] ON [PHONE_NUMBERS].PERSON_ID = [PERSONS].[ID]
	WHERE [PHONE_NUMBERS].[PHONE_NUMBER] LIKE '089%'


SELECT  [FIRST_NAME],
		[LAST_NAME] ,
		[PHONE_NUMBERS].[PHONE_NUMBER]
	FROM [PERSONS] AS [P]
	LEFT JOIN [PHONE_NUMBERS] ON [PHONE_NUMBERS].PERSON_ID = P.[ID]
	WHERE [PHONE_NUMBERS].[PHONE_NUMBER] LIKE '%9'

SELECT [FIRST_NAME],[LAST_NAME]
	FROM [PERSONS] 
	WHERE [FIRST_NAME] LIKE 'Х%' AND
			[LAST_NAME] LIKE 'П%'


SELECT [FIRST_NAME],[LAST_NAME]
	 FROM [PERSONS] 
	 WHERE [LAST_NAME] LIKE '%В'


SELECT * FROM [PHONE_TYPES]
SELECT * FROM [CITIES]
SELECT * FROM [PHONE_NUMBERS]
SELECT * FROM [PERSONS]
