USE [PhoneBook]
--TODO check select's for no lock
DECLARE @ZERO_UPDATE_COUNTER_COLUMN_VALUE INT =0;

BEGIN TRANSACTION base
	DECLARE @BURGAS_CITY_POSTAL_CODE INT = 8000 ;
	BEGIN TRY
		INSERT INTO [CITIES]
			([CITY_NAME],[AREA_NAME],[POSTAL_CODE], [UPDATE_COUNTER])
			VALUES
			('Бургас','Бургас',@BURGAS_CITY_POSTAL_CODE,@ZERO_UPDATE_COUNTER_COLUMN_VALUE)
PRINT('SUCCESS INSERT BURGAS!')
COMMIT TRANSACTION base
	END TRY
	BEGIN CATCH
		PRINT('ROLLED BACK')
ROLLBACK TRANSACTION base
	END CATCH


BEGIN TRANSACTION AddDefaultData
	BEGIN TRY

	DECLARE @PLOVDIV_CITY_POSTAL_CODE INT = 4000;
	DECLARE @VARNA_CITY_POSTAL_CODE INT = 9000;
	DECLARE @SOFIA_CITY_POSTAL_CODE INT = 1000;

	INSERT INTO [CITIES]
		([CITY_NAME],[AREA_NAME],[POSTAL_CODE], [UPDATE_COUNTER])
		VALUES
		('Пловдив', 'Пловдив',@PLOVDIV_CITY_POSTAL_CODE,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),	
		('Варна','Варна',@VARNA_CITY_POSTAL_CODE,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
		('София','София',@SOFIA_CITY_POSTAL_CODE,@ZERO_UPDATE_COUNTER_COLUMN_VALUE);
		

	DECLARE @PLOVDIV_CITY_ID INT = (select [ID] from CITIES WHERE [CITY_NAME] ='Пловдив');
	DECLARE @VARNA_CITY_ID INT =(SELECT [ID] FROM [CITIES] WHERE [CITY_NAME]='Варна');
	DECLARE @Burgas_CITY_ID INT =(SELECT [ID] FROM [CITIES] WHERE [CITY_NAME]='Бургас');
	DECLARE @SOFIA_CITY_ID INT =(SELECT [ID] FROM [CITIES] WHERE [CITY_NAME]='София');


	
	INSERT INTO [PERSONS]
	([FIRST_NAME],[SECOND_NAME],[LAST_NAME],[CITY_ID],[ADDRESS],[UPDATE_COUNTER],[UCN])
	VALUES
	('Трифон','Красимиров','Иванов',@PLOVDIV_CITY_ID,'Жк.Възраждане/Ул.Цар Калоян №24',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,9999999999),
	('Христо','Стоянов','Петров',@VARNA_CITY_ID,'Жк.Тракия/Ул.Лозенград №3',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,9999999999),
	('Георги','Ангелов','Анастасов',@Burgas_CITY_ID,'Жк.Лазур/Ул.Христо Ботев №9',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,9999999999),
	('Трифон','Красимиров','Иванов',@SOFIA_CITY_ID,'Жк.Студентски град/Ул.Парижка комуна №8',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,9999999999)
		
	INSERT INTO [PHONE_TYPES] 
	([PHONE_TYPE],[UPDATE_COUNTER]) VALUES
	('Home',@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
	('Mobile',@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
	('Work',@ZERO_UPDATE_COUNTER_COLUMN_VALUE)

	DECLARE @HOME_PHONE_TYPE_ID INT = (SELECT [ID] FROM PHONE_TYPES WHERE [PHONE_TYPE] ='Home');
	DECLARE @MOBILE_PHONE_TYPE_ID INT = (SELECT [ID] FROM PHONE_TYPES WHERE [PHONE_TYPE] ='Mobile');
	DECLARE @WORK_PHONE_TYPE_ID INT = (SELECT [ID] FROM PHONE_TYPES WHERE [PHONE_TYPE] ='Work');
		
			

	INSERT INTO [PHONE_NUMBERS]
		([PERSON_ID],[PHONE_NUMBER],[PHONE_TYPE_ID],[UPDATE_COUNTER])
		VALUES
		(1,'0893668829',@HOME_PHONE_TYPE_ID,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
		(2,'0899628177',@MOBILE_PHONE_TYPE_ID,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
		(3,'0876351840',@WORK_PHONE_TYPE_ID,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
		(4,'0882183197',@MOBILE_PHONE_TYPE_ID,@ZERO_UPDATE_COUNTER_COLUMN_VALUE)
		--DECLARE @BOOL BIT = 1;
		--		IF(@BOOL = 1)
		--		THROW 51000, 'The record does not exist.', 1; 
COMMIT TRANSACTION AddDefaultData
PRINT ('SUCCESS INSERT ALL DATA')
	END TRY
	BEGIN CATCH
	--SELECT ERROR_MESSAGE() AS ErrorMessage
		PRINT('ROLLED BACK')
ROLLBACK TRANSACTION AddDefaultData
	END CATCH


BEGIN TRANSACTION
	BEGIN TRY

	DECLARE @VELIKO_TARNOVO_POSTAL_CODE INT = 5000;
			INSERT INTO [CITIES]
					([CITY_NAME],[AREA_NAME],[POSTAL_CODE], [UPDATE_COUNTER])
					VALUES
					('Велико търново','Великотърновска',@VELIKO_TARNOVO_POSTAL_CODE,@ZERO_UPDATE_COUNTER_COLUMN_VALUE)
COMMIT
	END TRY
	BEGIN CATCH
		 SELECT ERROR_MESSAGE() AS ErrorMessage
ROLLBACK TRANSACTION
	END CATCH

--Exclusive Lock 
BEGIN TRANSACTION
	BEGIN TRY
		UPDATE [PERSONS] SET [ADDRESS] =
				'Жк.Славейков/Ул "Любен Каравелов №42"'
		WHERE [ADDRESS] = 
				'Жк.Студентски град/Ул.Парижка комуна №8'
		WAITFOR DELAY '00:00:10'
COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
ROLLBACK TRANSACTION
	END CATCH
SELECT * FROM [PERSONS] WITH (NOLOCK) 

BEGIN TRANSACTION
	BEGIN TRY
		UPDATE [PERSONS] SET [FIRST_NAME] ='Кирчо'
		WHERE [ADDRESS] = 
				'Жк.Славейков/Ул "Любен Каравелов №42"'
		WAITFOR DELAY '00:00:10'
COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
ROLLBACK TRANSACTION
	END CATCH

SELECT * FROM [PERSONS] WITH (NOLOCK) 


SELECT * FROM [PERSONS]

DELETE [PERSONS] WHERE [ADDRESS] = 'Жк.Славейков/Ул "Любен Каравелов №42"'

SELECT * FROM [PERSONS]

ROLLBACK TRANSACTION [CHANGE_PERSON_ADDRESS]

SELECT * FROM [PERSONS]


BEGIN TRANSACTION 
	BEGIN TRY
			UPDATE [PERSONS]
			SET [LAST_NAME] = 'Михайлов'
			WHERE [ID] = 4
		
			UPDATE [PHONE_NUMBERS]
				SET [PHONE_NUMBER] = '088611379'
				WHERE [PERSON_ID] = 4
COMMIT 
	END TRY
BEGIN CATCH
ROLLBACK TRANSACTION
 		SELECT ERROR_MESSAGE() AS ErrorMessage
END CATCH


BEGIN TRANSACTION
	BEGIN TRY
		SELECT * FROM [PERSONS]

			INSERT INTO [PERSONS]
						([FIRST_NAME],[SECOND_NAME],[LAST_NAME],[CITY_ID],[ADDRESS],[UPDATE_COUNTER],[UCN])
						VALUES
						('Стоян','Калинов','Стефанов',@Burgas_CITY_ID,'Жк.Възраждане/Ул.Пробуда №11',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,12345678904)
		SAVE TRANSACTION [TEST_TRANSACTION]
		DELETE FROM [PERSONS] WHERE [SECOND_NAME] ='Калинов'
		SELECT * FROM [PERSONS]
		ROLLBACK TRANSACTION [TEST_TRANSACTION]
		SELECT * FROM [PERSONS]
COMMIT
	END TRY
	BEGIN CATCH
ROLLBACK TRANSACTION
	 	SELECT ERROR_MESSAGE() AS ErrorMessage
	END CATCH



BEGIN TRANSACTION Insert_Georgi
	BEGIN TRY
		DECLARE @SELECTED_PERSON_ID INT =
			(SELECT [ID] FROM PERSONS
				WHERE
				[FIRST_NAME] ='Георги' AND
				[SECOND_NAME]='Ангелов' AND
				[LAST_NAME] = 'Анастасов')
				
		UPDATE [PERSONS]
			SET [CITY_ID] = 2
			WHERE
			[ID]= @SELECTED_PERSON_ID
		
		INSERT INTO [PERSONS]
		([FIRST_NAME],[SECOND_NAME],[LAST_NAME],[CITY_ID],[ADDRESS],[UPDATE_COUNTER],[UCN])
		VALUES
		('Петър','Калоянов','Стоянов',@PLOVDIV_CITY_ID,'Жк.Възраждане/Ул.Цар Калоян №24',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,null)
COMMIT TRANSACTION Insert_Georgi
	END TRY
	BEGIN CATCH
			SELECT ERROR_MESSAGE() AS ErrorMessage
ROLLBACK TRANSACTION Insert_Georgi
	
	END CATCH


DECLARE @ZERO_UPDATE_COUNTER_COLUMN_VALUE INT =0;
DECLARE @MOBILE_PHONE_TYPE_ID INT = (SELECT [ID] FROM PHONE_TYPES WHERE [PHONE_TYPE] ='Mobile');
DECLARE @SOFIA_CITY_ID INT =(SELECT [ID] FROM [CITIES] WHERE [CITY_NAME]='София');

BEGIN TRANSACTION Insert_People
	BEGIN TRY
		INSERT INTO [PERSONS] ([FIRST_NAME],
		[SECOND_NAME],
		[LAST_NAME],
		[UPDATE_COUNTER],
		[CITY_ID],
		[UCN]) values
		('Христо','Дамянов','Николов',@ZERO_UPDATE_COUNTER_COLUMN_VALUE,@SOFIA_CITY_ID,9123456789)

		DECLARE @PERSONS_HRISTO_DANQNOV_NIKOLOV_ID INT  = (SELECT [ID] FROM [PERSONS]WHERE
					[FIRST_NAME]= 'Христо' AND
					[SECOND_NAME] = 'Дамянов' AND
					[LAST_NAME] = 'Николов')

			BEGIN TRANSACTION 
				INSERT INTO [PHONE_NUMBERS] ([PERSON_ID],
				[PHONE_NUMBER],
				[PHONE_TYPE_ID],
				[UPDATE_COUNTER]) values
				(@PERSONS_HRISTO_DANQNOV_NIKOLOV_ID,'0873759275',@MOBILE_PHONE_TYPE_ID,@ZERO_UPDATE_COUNTER_COLUMN_VALUE);
			COMMIT TRANSACTION

			DECLARE @BOOL BIT = 1;
				IF(@BOOL = 1)
				THROW 51000, 'The record does not exist.', 1;  
COMMIT TRANSACTION Insert_People
		PRINT('SUCCESS COMMITED TRANSACTION')
	END TRY
	BEGIN CATCH
		PRINT('ROLLBACK TRANSACTION')
ROLLBACK TRANSACTION Insert_People
	END CATCH


INSERT INTO [CITIES]
	([CITY_NAME],[AREA_NAME],[POSTAL_CODE], [UPDATE_COUNTER])
	VALUES
	('Смолян', 'Смолян',1111,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),	
	('Приморско','Приморско',8002,@ZERO_UPDATE_COUNTER_COLUMN_VALUE),
	('Созопол','Созопол',9010,@ZERO_UPDATE_COUNTER_COLUMN_VALUE);