USE [PhoneBook]

--CREATE DATABASE [PhoneBook]

IF OBJECT_ID ('PERSONS') IS NOT NULL
BEGIN
	ALTER TABLE  [PERSONS]
	DROP CONSTRAINT IF EXISTS [FK_PERSONS_CITY_ID];
END


IF OBJECT_ID ('PHONE_NUMBERS') IS NOT NULL
BEGIN
	ALTER TABLE 	[PHONE_NUMBERS]
	DROP CONSTRAINT IF EXISTS	[FK_PHONE_NUMBERS_PERSON_ID], 
					[FK_PHONE_NUMBERS_PHONE_TYPE_ID];
END


DROP TABLE IF EXISTS [CITIES]
CREATE TABLE
	[CITIES]
	(
		[ID] INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER] INT NOT NULL,
		[CITY_NAME] NVARCHAR(32)NOT NULL,
		[AREA_NAME] NVARCHAR(32)NOT NULL,
		[POSTAL_CODE] INT NOT NULL,
		CONSTRAINT [PK_CITIES_ID]
		PRIMARY KEY ([ID])
	)

exec sp_AddExtendedProperty
'MS_Description',
'ID ->Уникален идентификатор на запис в таблицата',
'SCHEMA', 'dbo',
'TABLE', 'CITIES',
'COLUMN', 'ID'


DROP TABLE IF EXISTS [PHONE_TYPES]
CREATE TABLE
	[PHONE_TYPES]
	(
		[ID] INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER] INT NOT NULL,
		[PHONE_TYPE] VARCHAR(16) UNIQUE NOT NULL,
		CONSTRAINT [PK_PHONE_TYPES_ID]
		PRIMARY KEY ([ID])
	)


DROP TABLE IF EXISTS [PERSONS]
CREATE TABLE
	[PERSONS]
	(
		[ID] INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER] INT NOT NULL,
		[FIRST_NAME] NVARCHAR(32) NOT NULL,
		[SECOND_NAME] NVARCHAR(32) NOT NULL,
		[LAST_NAME] NVARCHAR(32) NOT NULL,
		[EGN] NVARCHAR(16) NOT NULL,		
		[CITY_ID] INT NOT NULL,
		[ADDRESS] NVARCHAR(256) NOT NULL,	
		CONSTRAINT [PK_PERSONS_ID]
		PRIMARY KEY ([ID])
	)

DROP TABLE IF EXISTS [PHONE_NUMBERS]
CREATE TABLE
	[PHONE_NUMBERS]
	(
		[ID] INT IDENTITY (1,1) NOT NULL, 
		[UPDATE_COUNTER] INT NOT NULL,
		[PERSON_ID] INT NOT NULL,
		[PHONE_TYPE_ID] INT NOT NULL,
		[PHONE_NUMBER] VARCHAR(16) NOT NULL UNIQUE,
		CONSTRAINT [PK_PHONE_NUMBERS_ID]
			PRIMARY KEY([ID])
	)

ALTER TABLE [PERSONS]
ADD CONSTRAINT [FK_PERSONS_CITY_ID] 
		FOREIGN KEY ([CITY_ID])
		REFERENCES [CITIES]([ID])

ALTER TABLE [PHONE_NUMBERS]
ADD CONSTRAINT [FK_PHONE_NUMBERS_PERSON_ID]
			FOREIGN KEY  ([PERSON_ID]) 
			REFERENCES [PERSONS] ([ID])
			ON DELETE CASCADE,

		CONSTRAINT [FK_PHONE_NUMBERS_PHONE_TYPE_ID]
			FOREIGN KEY ([PHONE_TYPE_ID])
			REFERENCES [PHONE_TYPES] ([ID])