USE [PhoneBook]

--CREATE DATABASE [PhoneBook]

--IF OBJECT_ID ('PERSONS') IS NOT NULL
--BEGIN
--	ALTER TABLE  [PERSONS]
--	DROP CONSTRAINT IF EXISTS [FK_PERSONS_CITY_ID];
--END


--IF OBJECT_ID ('PHONE_NUMBERS') IS NOT NULL
--BEGIN
--	ALTER TABLE 	[PHONE_NUMBERS]
--	DROP CONSTRAINT IF EXISTS	[FK_PHONE_NUMBERS_PERSON_ID], 
--					[FK_PHONE_NUMBERS_PHONE_TYPE_ID];
--END


DROP TABLE IF EXISTS [PHONE_NUMBERS]
DROP TABLE IF EXISTS [PERSONS]
DROP TABLE IF EXISTS [CITIES]
DROP TABLE IF EXISTS [PHONE_TYPES]

CREATE TABLE
	[CITIES]
	(
		[ID] INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER] INT NOT NULL,
		[CITY_NAME] NVARCHAR(32)NOT NULL UNIQUE,
		[AREA_NAME] NVARCHAR(32)NOT NULL,
		[POSTAL_CODE] INT NOT NULL,
		CONSTRAINT [PK_CITIES_ID]
		PRIMARY KEY ([ID])
	)

exec sp_AddExtendedProperty
'MS_Description',
'Уникален идентификатор на запис в таблицата (32)бита',
'SCHEMA', 'dbo',
'TABLE', 'CITIES',
'COLUMN', 'ID'

exec sp_AddExtendedProperty
'MS_Description',
'Версия на ред (32)бита',
'SCHEMA', 'dbo',
'TABLE', 'CITIES',
'COLUMN', 'UPDATE_COUNTER'

exec sp_addextendedproperty
'MS_Description',
'Таблица съдържаща областите (512)бита',
'SCHEMA', 'dbo',
'TABLE', 'CITIES',
'COLUMN', 'CITY_NAME'

exec sp_addextendedproperty
'MS_Description',
'Таблица съдържаща градовете (512)бита',
'SCHEMA', 'dbo',
'TABLE', 'CITIES',
'COLUMN', 'AREA_NAME'

exec sp_addextendedproperty
'MS_Description',
'Таблица съдържаща пощенските кодове (32)бита',
'SCHEMA', 'dbo',
'TABLE', 'CITIES',
'COLUMN', 'POSTAL_CODE'



CREATE TABLE
	[PHONE_TYPES]
	(
		[ID] INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER] INT NOT NULL,
		[PHONE_TYPE] VARCHAR(16) UNIQUE NOT NULL,
		CONSTRAINT [PK_PHONE_TYPES_ID]
		PRIMARY KEY ([ID])
	)

exec sp_addextendedproperty
'MS_Description',
'Уникален идентификатор на запис в таблицата (32)бита',
'SCHEMA', 'dbo',
'TABLE', 'PHONE_TYPES',
'COLUMN', 'ID'

exec sp_addextendedproperty
'MS_Description',
'Версия на ред (32)бита',
'SCHEMA', 'dbo',
'TABLE', 'PHONE_TYPES',
'COLUMN', 'UPDATE_COUNTER'

exec sp_addextendedproperty
'MS_Description',
'Колона съдържаща типовете телефони(128)бита',
'SCHEMA', 'dbo',
'TABLE', 'PHONE_TYPES',
'COLUMN', 'PHONE_TYPE'

CREATE TABLE
	[PERSONS]
	(
		[ID] INT IDENTITY (1,1) NOT NULL,
		[UPDATE_COUNTER] INT NOT NULL,
		[FIRST_NAME] NVARCHAR(32) NOT NULL,
		[SECOND_NAME] NVARCHAR(32) NOT NULL,
		[LAST_NAME] NVARCHAR(32) NOT NULL,
		[EGN] NVARCHAR(16) NOT NULL,		
		[CITY_ID] INT NOT NULL,
		[ADDRESS] NVARCHAR(256) NOT NULL,	
		CONSTRAINT [PK_PERSONS_ID]
		PRIMARY KEY ([ID])
	)

CREATE TABLE
	[PHONE_NUMBERS]
	(
		[ID] INT IDENTITY (1,1) NOT NULL, 
		[UPDATE_COUNTER] INT NOT NULL,
		[PERSON_ID] INT NOT NULL,
		[PHONE_TYPE_ID] INT NOT NULL,
		[PHONE_NUMBER] VARCHAR(16) NOT NULL UNIQUE,
		CONSTRAINT [PK_PHONE_NUMBERS_ID]
			PRIMARY KEY([ID])
	)

ALTER TABLE [PERSONS]
ADD CONSTRAINT [FK_PERSONS_CITY_ID] 
		FOREIGN KEY ([CITY_ID])
		REFERENCES [CITIES]([ID])

ALTER TABLE [PHONE_NUMBERS]
ADD CONSTRAINT [FK_PHONE_NUMBERS_PERSON_ID]
			FOREIGN KEY  ([PERSON_ID]) 
			REFERENCES [PERSONS] ([ID])
			ON DELETE CASCADE,

		CONSTRAINT [FK_PHONE_NUMBERS_PHONE_TYPE_ID]
			FOREIGN KEY ([PHONE_TYPE_ID])
			REFERENCES [PHONE_TYPES] ([ID])