USE [PhoneBook]

CREATE OR ALTER PROCEDURE SP_ADD_TABLE_DESCRIPTION
(
    @TABLE_NAME NVARCHAR(100),
    @TABLE_DESCRIPTION NVARCHAR(100)
)
AS
BEGIN
    SELECT CONCAT(@TABLE_NAME,'_TABLE_DESCRIPTION') AS DESCRIPTION_NAME

    EXEC SP_ADDEXTENDEDPROPERTY @NAME=DESCRIPTION_NAME,
                                @VALUE=@TABLE_DESCRIPTION,
                                @LEVEL0TYPE=N'SCHEMA',
                                @LEVEL0NAME=N'dbo',
                                @LEVEL1TYPE=N'TABLE',
                                @LEVEL1NAME=@TABLE_NAME
END

CREATE OR ALTER PROCEDURE SP_ADD_COLUMN_DESCRIPTION
(
	@TABLE_NAME NVARCHAR(128),
	@COLUMN_NAME NVARCHAR(128),
	@COLUMN_DESCRIPTION NVARCHAR(128)
)
AS
BEGIN
	exec sp_AddExtendedProperty'MS_Description',@COLUMN_DESCRIPTION,
								'SCHEMA', 'dbo',
								'TABLE', @TABLE_NAME,
								'COLUMN', @COLUMN_NAME
END